# Change these first
owner: aaronkebede # Your GitHub organization or username, where this repository lives
repo: s # The name of this repository

sites:
  - name: St John's E Learning Platform
    url: https://learn.stjohn.edu.et
  - name: St John's Home Page
    url: https://stjohn.edu.et
  - name: St John Email
    url: https://mail.goole.com/a/stjohn.edu.et
  - name: St John's Servers
    url: https://home.stjohn.edu.et

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: sys.stjohn.edu.et
  # baseUrl: /your-repo-name
  logoUrl: https://stjohn.edu.et/images/logo.png
  name: St John System Status
  introTitle: Discover the status of our systems.
  introMessage: This is a status page which uses **real-time** data to check for availablity of our systems.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://stjohn.edu.et
    - title: E-learn
      href: https://learn.stjohn.edu.et
    - title: Docs
      href: https://wiki.stjohn.edu.et

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
